### ISSUE TITLE
redundant version info for artefact

### ISSUE THREAD

**Issue by k3muri84** [jin/rules_maven#3]
The versions of the artifacts need to be specified twice in WORKSPACE and BUILD files
Would be easier to maintain bigger project to use a key for one artifact.

**Comment by jin** [comment]
The idea for this is to be very explicit about the dependencies in your BUILD files. You can have two `android_binary` targets depending on different versions of guava, for example.

Do you have an example API on what you're thinking of?

**Comment by k3muri84** [comment]
It actually can probably be done with starlark. creating a dictionary of versions. Will any object from WORKSPACE be available on BUILD ?

**Comment by jin** [comment]
You can do so by creating a Starlark `.bzl` file, defining the dictionary like this: https://github.com/jin/android-bazel-java-app-template-1/blob/master/versions.bzl

Then use them in the WORKSPACE: https://github.com/jin/android-bazel-java-app-template-1/blob/aa271f030fd6bdd23511959cca821e0d4becf99d/WORKSPACE#L17

or in the BUILD file: https://github.com/jin/android-bazel-java-app-template-1/blob/aa271f030fd6bdd23511959cca821e0d4becf99d/src/main/BUILD#L2
